name: Build and Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install dependencies
        run: |
          echo "Installing dependencies..."
          npm install --verbose
          echo "Creating git config..."
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          echo "Adding package-lock.json..."
          git add package-lock.json
          echo "Committing changes..."
          git commit -m "Add package-lock.json" || echo "No changes to commit"
          echo "Pushing changes..."
          git push origin main || echo "No changes to push"

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2